### ISSUE TITLE
Floating point array zeroing

### ISSUE THREAD

**Issue by ravenexp** [swilmet/glib-gtk-book#2]
From 2.1.4:

> If it isn’t obvious: g_malloc0() fills raw memory with unset bits, not the value 0 for whatever type you intend to put there. Occasionally someone expects to get an array of floating point numbers initialized to 0.0; this will not work.

Why is that? It should work on the computers using IEEE floating point numbers, which is like 99.7% of all computers.

**Comment by kozross** [comment]
This is an unfortunate side-effect of the fact that the C89 standard doesn't specify whether this behaviour is to be honoured or not. Unfortunately, due to Micro$atan's retarded intransigence on this matter, GLib cannot assume this either, as C89 is still the lowest common denominator on this.

**Comment by ravenexp** [comment]
I still think the wording is too strong in this one. The book states as a fact that it won't work, when in reality it will work on all platforms GTK+ is relevant on. Both gcc and Microsoft compilers use IEEE floats even though Microsoft only claims to support C89.

**Comment by swilmet** [comment]
Thanks for the bug report. Sorry for the late reply, I think my GitHub settings were configured to not receive any e-mails. Should be fixed now.

I'll look at the issue for the next version and come up with a better explanation.

**Comment by swilmet** [comment]
Fixed, see the commit above.
